# Generated by Django 5.1.1 on 2024-09-29 14:10

import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='net_cost',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('gross_cost'), '*', django.db.models.expressions.CombinedExpression(models.F('tax_applicable'), '+', models.Value(Decimal('1')))), output_field=models.DecimalField(decimal_places=2, max_digits=12)),
        ),
    ]
