repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.6.8'
    hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

  - repo: https://github.com/asottile/add-trailing-comma
    rev: 'v3.1.0'
    hooks:
    - id: add-trailing-comma
      exclude: "migrations"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
