name: app

services:
  app:
    build:
      context: .
      dockerfile: ./compose/test/Dockerfile
    image: app
    container_name: app
    restart: always
    depends_on:
      - postgres-db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file:
      - .env
    tty: true
    stdin_open: true

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    volumes:
      - test-postgres-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  test-postgres-db-data:
