name: shop

services:
  app:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: shop-app
    container_name: shop-app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - postgres-db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    tty: true
    stdin_open: true
    command: ["/start"]

  postgres-db:
    image: postgres:16
    container_name: shop-postgres-db
    volumes:
      - shop-postgres-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  shop-postgres-db-data:
