name: access_guard

services:
  app:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: access_guard-app
    container_name: access_guard-app
    restart: always
    depends_on:
      - postgres-db
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: [ "/start" ]

  postgres-db:
    image: postgres:16
    container_name: access_guard-postgres-db
    volumes:
      - access_guard-postgres-db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  access_guard-postgres-db-data:
