name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-directory --no-root --with test

      - name: Lint with Ruff
        run: |
          ruff check --output-format=github .
        continue-on-error: true

      - name: Formater with Ruff
        run: |
          ruff format --check .
        continue-on-error: true

      - name: Test with pytest
        run: |
          pytest
