name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
        POSTGRES_HOST: localhost
        POSTGRES_DB: example-db-db
        POSTGRES_USER: example-user-db
        POSTGRES_PASSWORD: example-password-db

    services:
      postgres-db:
        image: postgres:16
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-directory --no-root --with test

      - name: Lint and Format with Ruff
        run: |
          ruff check --output-format=github .
          ruff format --check .
        continue-on-error: true

      - name: Run database migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest
